### PR TITLE
Update to 1.1.14

### PR DESCRIPTION
**Pull request by ids1024**
Previously we had an unreleased version of egl-wayland here. Now an upstream release has been tagged, with a couple additional changes.

### CODE REVIEW

**Review by mmstick — APPROVED** [review]

**Comment by Drakulix** [comment]
Note that this version apparently has issues: https://github.com/NVIDIA/egl-wayland/issues/117

**Comment by heftig** [comment]
From what I can tell from the PR diff, the "unreleased version" that is currently in this repository should already suffer from those issues, so you're not making it worse by merging this.

**Comment by ids1024** [comment]
Yeah, these couple commits won't introduce issues like that.

Looks like that's actually a Firefox bug, as mentioned in the other issue that links: https://bugzilla.mozilla.org/show_bug.cgi?id=1898476

We can make sure not to enable explicit sync in cosmic-comp until there's a version of Firefox with that fix, I guess.

**Comment by Drakulix** [comment]
> We can make sure not to enable explicit sync in cosmic-comp until there's a version of Firefox with that fix, I guess.

Right, this should only trigger once we support the required protocol. Then this is good to merge I guess.

**Comment by ids1024** [comment]
https://github.com/NVIDIA/egl-wayland/releases/tag/1.1.15 apparently fixes those issues.

**Comment by ids1024** [comment]
Closing in favor of https://github.com/pop-os/egl-wayland/pull/5.

**Pull request closed without merging**
